"""
Objective:

1. Extract all the data labels effectively. Multi-hot encode the labels that have multiple encodings.
2. Determine which entries are duplicates by value
"""

############################################ SEEDS ###############################################
import numpy as np

mhe_seeds_dict = [
    "acerbic",
    "aggressive",
    "agreeable",
    "airy",
    "ambitious",
    "amiable/good-natured",
    "angry",
    "angst-ridden",
    "anguished/distraught",
    "angular",
    "animated",
    "anthemic",
    "apocalyptic",
    "arid",
    "athletic",
    "atmospheric",
    "austere",
    "autumnal",
    "belligerent",
    "benevolent",
    "bitter",
    "bittersweet",
    "bleak",
    "boisterous",
    "bombastic",
    "bouncy",
    "brash",
    "brassy",
    "bravado",
    "bright",
    "brittle",
    "brooding",
    "calm/peaceful",
    "campy",
    "capricious",
    "carefree",
    "cartoonish",
    "cathartic",
    "celebratory",
    "cerebral",
    "cheerful",
    "child-like",
    "circular",
    "clinical",
    "cold",
    "comic",
    "complex",
    "concise",
    "confessional",
    "confident",
    "confrontational",
    "cosmopolitan",
    "crunchy",
    "cute",
    "cynical/sarcastic",
    "dark",
    "declamatory",
    "defiant",
    "delicate",
    "demonic",
    "desperate",
    "detached",
    "devotional",
    "difficult",
    "dignified/noble",
    "dissonant",
    "dramatic",
    "dreamy",
    "driving",
    "druggy",
    "earnest",
    "earthy",
    "ebullient",
    "eccentric",
    "ecstatic",
    "eerie",
    "effervescent",
    "elaborate",
    "elegant",
    "elegiac",
    "energetic",
    "enigmatic",
    "epic",
    "erotic",
    "ethereal",
    "euphoric",
    "exciting",
    "exotic",
    "exploratory",
    "explosive",
    "extroverted",
    "exuberant",
    "fantastic/fantasy-like",
    "feral",
    "feverish",
    "fierce",
    "fiery",
    "flashy",
    "flowing",
    "fractured",
    "freewheeling",
    "fun",
    "funereal",
    "gentle",
    "giddy",
    "gleeful",
    "gloomy",
    "graceful",
    "greasy",
    "grim",
    "gritty",
    "gutsy",
    "happy",
    "harsh",
    "heavy",
    "hedonistic",
    "heroic",
    "hostile",
    "humorous",
    "hungry",
    "hymn-like",
    "hyper",
    "hypnotic",
    "improvisatory",
    "indulgent",
    "innocent",
    "insular",
    "intense",
    "intimate",
    "introspective",
    "ironic",
    "irreverent",
    "jovial",
    "joyous",
    "kinetic",
    "knotty",
    "laid-back/mellow",
    "languid",
    "lazy",
    "light",
    "literate",
    "lively",
    "lonely",
    "loose",
    "lush",
    "lyrical",
    "macabre",
    "magical",
    "majestic",
    "malevolent",
    "manic",
    "marching",
    "martial",
    "meandering",
    "mechanical",
    "meditative",
    "melancholy",
    "melodic",
    "menacing",
    "messy",
    "mighty",
    "monastic",
    "monumental",
    "motoric",
    "mysterious",
    "mystical",
    "naive",
    "narcotic",
    "narrative",
    "negative",
    "nervous/jittery",
    "nihilistic",
    "nocturnal",
    "nostalgic",
    "ominous",
    "optimistic",
    "opulent",
    "organic",
    "ornate",
    "outraged",
    "outrageous",
    "paranoid",
    "passionate",
    "pastoral",
    "patriotic",
    "perky",
    "philosophical",
    "plain",
    "plaintive",
    "playful",
    "poetic",
    "poignant",
    "positive",
    "powerful",
    "precious",
    "provocative",
    "pulsing",
    "pure",
    "quaint",
    "quirky",
    "radiant",
    "rambunctious",
    "ramshackle",
    "raucous",
    "reassuring/consoling",
    "rebellious",
    "reckless",
    "refined",
    "reflective",
    "regretful",
    "relaxed",
    "reserved",
    "resolute",
    "restrained",
    "reverent",
    "rhapsodic",
    "rollicking",
    "romantic",
    "rousing",
    "rowdy",
    "rustic",
    "sacred",
    "sad",
    "sarcastic",
    "sardonic",
    "satirical",
    "savage",
    "scary",
    "scattered",
    "searching",
    "seductive",
    "self-conscious",
    "sensual",
    "sentimental",
    "serious",
    "severe",
    "sexual",
    "sexy",
    "shimmering",
    "silly",
    "sleazy",
    "slick",
    "smooth",
    "snide",
    "soft/quiet",
    "somber",
    "soothing",
    "sophisticated",
    "spacey",
    "spacious",
    "sparkling",
    "sparse",
    "spicy",
    "spiritual",
    "spontaneous",
    "spooky",
    "sprawling",
    "sprightly",
    "springlike",
    "stately",
    "street-smart",
    "striding",
    "strong",
    "stylish",
    "suffocating",
    "sugary",
    "summery",
    "sunny",
    "suspenseful",
    "swaggering",
    "sweet",
    "swinging",
    "technical",
    "tender",
    "tense/anxious",
    "theatrical",
    "thoughtful",
    "threatening",
    "thrilling",
    "tight",
    "tough",
    "tragic",
    "transparent/translucent",
    "trashy",
    "trippy",
    "triumphant",
    "turbulent",
    "uncompromising",
    "understated",
    "unsettling",
    "uplifting",
    "urgent",
    "virile",
    "visceral",
    "volatile",
    "vulgar",
    "vulnerable",
    "warm",
    "weary",
    "whimsical",
    "wintry",
    "wistful",
    "witty",
    "wry",
    "yearning",
]


# Developing multi-hot encoding (MHE) for seeds
def mhe_encoding_seeds(track_seeds, seed_to_index):
    vector = np.zeros(len(seed_to_index))
    for seed in track_seeds:
        if seed in seed_to_index:
            vector[seed_to_index[seed]] = 1
    return vector


############################################ GENRES ###############################################
import numpy as np

mhe_genres_dict = [
    "rap",
    "metal",
    "hip-hop",
    "nu metal",
    "singer-songwriter",
    "punk",
    "industrial",
    "metalcore",
    "alternative metal",
    "classic rock",
    "electroclash",
    "rock",
    "post-hardcore",
    "progressive metal",
    "indie rock",
    "indie pop",
    "indie",
    "pop",
    "post-punk",
    "thrash metal",
    "industrial metal",
    "gothic metal",
    "death metal",
    "alternative rock",
    "screamo",
    "noise rock",
    "electronic",
    "riot grrrl",
    "electro",
    "symphonic metal",
    "grunge",
    "trip-hop",
    "hard rock",
    "breakbeat",
    "melodic death metal",
    "hip hop",
    "hardcore",
    "alternative",
    "experimental",
    "country",
    "stoner rock",
    "horrorcore",
    "ska",
    "black metal",
    "dark electro",
    "redneck",
    "hardcore punk",
    "stoner metal",
    "ambient",
    "underground hip hop",
    "math rock",
    "grindcore",
    "doom metal",
    "noise pop",
    "emo",
    "deathcore",
    "ebm",
    "post-metal",
    "goth",
    "bluegrass",
    "british",
    "christian metal",
    "soul",
    "industrial rock",
    "folk",
    "digital hardcore",
    "post-rock",
    "visual kei",
    "dance",
    "britpop",
    "german",
    "mathcore",
    "blues rock",
    "melodic hardcore",
    "minimal techno",
    "new wave",
    "avant-garde",
    "pop punk",
    "groove metal",
    "christian rock",
    "j-rock",
    "funk",
    "breakcore",
    "folk metal",
    "crust punk",
    "funk metal",
    "acoustic",
    "oi",
    "soundtrack",
    "idm",
    "melodic black metal",
    "drum and bass",
    "anime",
    "electro-industrial",
    "blues",
    "k-pop",
    "d-beat",
    "aggrotech",
    "dubstep",
    "rockabilly",
    "house",
    "power metal",
    "art pop",
    "progressive rock",
    "noise",
    "gothic rock",
    "sludge metal",
    "psychobilly",
    "electronic rock",
    "spanish",
    "piano rock",
    "piano",
    "dark cabaret",
    "experimental rock",
    "horror punk",
    "lo-fi",
    "dance rock",
    "folk punk",
    "summer",
    "comedy",
    "jazz",
    "depressive black metal",
    "poetry",
    "cybergrind",
    "pop rock",
    "powerviolence",
    "sad",
    "finnish metal",
    "classical",
    "electronica",
    "grime",
    "shoegaze",
    "crunk",
    "guitar",
    "rock en espanol",
    "slowcore",
    "violin",
    "spoken word",
    "neofolk",
    "psychedelic rock",
    "canadian rock",
    "dream pop",
    "technical death metal",
    "madchester",
    "garage rock",
    "drone",
    "progressive black metal",
    "downtempo",
    "french",
    "synthwave",
    "worship",
    "contemporary classical",
    "zeuhl",
    "vocal trance",
    "mpb",
    "latin",
    "trance",
    "techno",
    "chill",
    "cabaret",
    "ambient pop",
    "breaks",
    "r&b",
    "world",
    "krautrock",
    "reggae",
    "boogie",
    "soft rock",
    "washboard",
    "video game music",
    "disco",
    "minimal synth",
    "dark ambient",
    "art rock",
    "medieval",
    "darkstep",
    "erhu",
    "hardstyle",
    "j-pop",
    "groove",
    "garage",
    "martial industrial",
    "russian alternative",
    "minimalism",
    "new weird america",
    "symphonic rock",
    "atmospheric black metal",
    "jungle",
    "neoclassical darkwave",
    "deathrock",
    "psychedelic pop",
    "experimental folk",
    "trip hop",
    "progressive house",
    "ritual ambient",
    "celtic",
    "free jazz",
    "water",
    "cyberpunk",
    "halloween",
    "soundtracks",
    "orchestra",
    "skate punk",
    "teen pop",
    "afrobeat",
    "new age",
    "electropop",
    "dancehall",
    "quran",
    "atmosphere",
    "a cappella",
    "southern rock",
    "happy",
    "french rock",
    "funk carioca",
    "electro house",
    "world fusion",
    "garage punk",
    "underground rap",
    "choral",
    "folktronica",
    "latin rock",
    "brazil",
    "symphonic death metal",
    "glitch hop",
    "drone metal",
    "synthpop",
    "hard trance",
    "glam rock",
    "meme rap",
    "bossa nova",
    "witch house",
    "sleep",
    "dark jazz",
    "post-black metal",
    "trap",
    "dark wave",
    "cello",
    "harp",
    "hip house",
    "hauntology",
    "easy listening",
    "acid jazz",
    "futurepop",
    "western swing",
    "melodic rap",
    "ambient black metal",
    "glitch",
    "music box",
    "avant-garde jazz",
    "indietronica",
    "accordion",
    "lullaby",
    "deep ambient",
    "disney",
    "psychedelic trance",
    "alternative country",
    "folk rock",
    "lounge",
    "beats",
    "alternative pop",
    "dub",
    "abstract",
    "minimal wave",
    "space rock",
    "nu jazz",
    "uk garage",
    "coldwave",
    "turntablism",
    "lilith",
    "power electronics",
    "swing",
    "northern soul",
    "kids",
    "novelty",
    "steampunk",
    "calypso",
    "russian rock",
    "goregrind",
    "gypsy",
    "ccm",
    "neurofunk",
    "tango",
    "west coast rap",
    "celtic rock",
    "chanson",
    "alternative dance",
    "8-bit",
    "french pop",
    "nederpop",
    "outsider",
    "swedish",
    "chamber pop",
    "vocal jazz",
    "ukulele",
    "indie folk",
    "chillwave",
    "praise",
    "songwriter",
    "tex-mex",
    "native american",
    "meditation",
    "smooth jazz",
    "psychill",
    "organic ambient",
    "big beat",
    "opera",
    "zen",
    "noisecore",
    "djent",
    "bachata",
    "freak folk",
    "balearic",
    "ska punk",
    "romance",
    "power pop",
    "houston rap",
    "vaporwave",
    "post-grunge",
    "rock nacional",
    "chillstep",
    "ambient industrial",
    "dark folk",
    "jazz fusion",
    "mandolin",
    "jangle pop",
    "broken beat",
    "klezmer",
    "street punk",
    "doo-wop",
    "motown",
    "merseybeat",
    "straight edge",
    "gospel",
    "chiptune",
    "polka",
    "jam band",
    "minecraft",
    "gypsy punk",
    "parody",
    "suomisaundi",
    "gypsy jazz",
    "rhythm and blues",
    "samba",
    "merengue",
    "baroque",
    "taiko",
    "spanish classical",
    "hawaiian",
    "flamenco",
    "rumba",
    "fado",
    "schlager",
    "turkish",
    "latin jazz",
    "fingerstyle",
    "qawwali",
    "broadway",
    "focus",
    "rave",
    "crack rock steady",
    "big band",
    "contemporary jazz",
    "party",
    "freestyle",
    "latin pop",
    "progressive breaks",
    "eurodance",
    "no wave",
    "brass band",
    "modern rock",
    "club",
    "polish rock",
    "celtic punk",
    "soca",
    "boogaloo",
    "neo soul",
    "electro jazz",
    "psychedelic folk",
    "indian",
    "garage rock revival",
    "tropicalia",
    "jazz funk",
    "anti-folk",
    "future garage",
    "demoscene",
    "goa trance",
    "progressive trance",
    "moog",
    "deep house",
    "space age pop",
    "tech house",
    "yoga",
    "deep techno",
    "sufi",
    "dark disco",
    "new jack swing",
]


# Developing multi-hot encoding (MHE) for genres
def mhe_encoding_genres(track_genres, genre_to_index):
    vector = np.zeros(len(genre_to_index))
    for genre in track_genres:
        if genre in genre_to_index:
            vector[genre_to_index[genre]] = 1
    return vector


############################################# CSV ################################################
import json
import csv

uncleaned_dataset_path = r"server\model\available_unclean_dataset.json"

with open(uncleaned_dataset_path, "r") as f:
    uncleaned_dataset = json.load(f)

# for data in uncleaned_dataset:
#     genre = data.get("genre")

#     if genre not in mhe_genres_dict:
#         mhe_genres_dict.append(genre)

# print("Done")
# print(mhe_genres_dict)

# CSV Headers (need to add seed mhe)
csv_headers = (
    [
        "index",
        "track",
        "artist",
        "number_of_emotion_tags",
        "valence_tags",
        "arousal_tags",
        "dominance_tags",
        "spotify_id",
        "tempo",
        "tempo_bt",
        "rms_mean",
        "rms_std",
        "rms_min",
        "rms_max",
        "zcr_mean",
        "zcr_std",
        "zcr_min",
        "zcr_max",
        "spec_centroid_mean",
        "spec_centroid_std",
        "spec_centroid_min",
        "spec_centroid_max",
        "spec_bandwidth_mean",
        "spec_bandwidth_std",
        "spec_bandwidth_min",
        "spec_bandwidth_max",
        "spec_contrast_1_mean",
        "spec_contrast_1_std",
        "spec_contrast_1_min",
        "spec_contrast_1_max",
        "spec_contrast_2_mean",
        "spec_contrast_2_std",
        "spec_contrast_2_min",
        "spec_contrast_2_max",
        "spec_contrast_3_mean",
        "spec_contrast_3_std",
        "spec_contrast_3_min",
        "spec_contrast_3_max",
        "spec_contrast_4_mean",
        "spec_contrast_4_std",
        "spec_contrast_4_min",
        "spec_contrast_4_max",
        "spec_contrast_5_mean",
        "spec_contrast_5_std",
        "spec_contrast_5_min",
        "spec_contrast_5_max",
        "spec_contrast_6_mean",
        "spec_contrast_6_std",
        "spec_contrast_6_min",
        "spec_contrast_6_max",
        "spec_contrast_7_mean",
        "spec_contrast_7_std",
        "spec_contrast_7_min",
        "spec_contrast_7_max",
        "spec_flatness_mean",
        "spec_flatness_std",
        "spec_flatness_min",
        "spec_flatness_max",
        "spec_rolloff_mean",
        "spec_rolloff_std",
        "spec_rolloff_min",
        "spec_rolloff_max",
        "mfcc_1_mean",
        "mfcc_1_std",
        "mfcc_1_min",
        "mfcc_1_max",
        "mfcc_2_mean",
        "mfcc_2_std",
        "mfcc_2_min",
        "mfcc_2_max",
        "mfcc_3_mean",
        "mfcc_3_std",
        "mfcc_3_min",
        "mfcc_3_max",
        "mfcc_4_mean",
        "mfcc_4_std",
        "mfcc_4_min",
        "mfcc_4_max",
        "mfcc_5_mean",
        "mfcc_5_std",
        "mfcc_5_min",
        "mfcc_5_max",
        "mfcc_6_mean",
        "mfcc_6_std",
        "mfcc_6_min",
        "mfcc_6_max",
        "mfcc_7_mean",
        "mfcc_7_std",
        "mfcc_7_min",
        "mfcc_7_max",
        "mfcc_8_mean",
        "mfcc_8_std",
        "mfcc_8_min",
        "mfcc_8_max",
        "mfcc_9_mean",
        "mfcc_9_std",
        "mfcc_9_min",
        "mfcc_9_max",
        "mfcc_10_mean",
        "mfcc_10_std",
        "mfcc_10_min",
        "mfcc_10_max",
        "mfcc_11_mean",
        "mfcc_11_std",
        "mfcc_11_min",
        "mfcc_11_max",
        "mfcc_12_mean",
        "mfcc_12_std",
        "mfcc_12_min",
        "mfcc_12_max",
        "mfcc_13_mean",
        "mfcc_13_std",
        "mfcc_13_min",
        "mfcc_13_max",
        "chromagram_1_mean",
        "chromagram_1_std",
        "chromagram_1_min",
        "chromagram_1_max",
        "chromagram_2_mean",
        "chromagram_2_std",
        "chromagram_2_min",
        "chromagram_2_max",
        "chromagram_3_mean",
        "chromagram_3_std",
        "chromagram_3_min",
        "chromagram_3_max",
        "chromagram_4_mean",
        "chromagram_4_std",
        "chromagram_4_min",
        "chromagram_4_max",
        "chromagram_5_mean",
        "chromagram_5_std",
        "chromagram_5_min",
        "chromagram_5_max",
        "chromagram_6_mean",
        "chromagram_6_std",
        "chromagram_6_min",
        "chromagram_6_max",
        "chromagram_7_mean",
        "chromagram_7_std",
        "chromagram_7_min",
        "chromagram_7_max",
        "chromagram_8_mean",
        "chromagram_8_std",
        "chromagram_8_min",
        "chromagram_8_max",
        "chromagram_9_mean",
        "chromagram_9_std",
        "chromagram_9_min",
        "chromagram_9_max",
        "chromagram_10_mean",
        "chromagram_10_std",
        "chromagram_10_min",
        "chromagram_10_max",
        "chromagram_11_mean",
        "chromagram_11_std",
        "chromagram_11_min",
        "chromagram_11_max",
        "chromagram_12_mean",
        "chromagram_12_std",
        "chromagram_12_min",
        "chromagram_12_max",
    ]
    + mhe_genres_dict
    + mhe_seeds_dict
)

csv_file_path = "server\model\music_dataset.csv"

# Writes the csv file containing both the semantic and auditory data for all the samples
def write_csv():
    row_count = 0

    with open(csv_file_path, "w", newline="", encoding="utf-8") as music_csv:
        writer = csv.DictWriter(music_csv, fieldnames=csv_headers)
        writer.writeheader()

        index = 0

        for track in uncleaned_dataset:
            row = {
                "index": index,
                "track": track.get("track"),
                "artist": track.get("artist"),
                "number_of_emotion_tags": track.get("number_of_emotion_tags"),
                "valence_tags": track.get("valence_tags"),
                "arousal_tags": track.get("arousal_tags"),
                "dominance_tags": track.get("dominance_tags"),
                "spotify_id": track.get("spotify_id"),
                "tempo": track.get("tempo"),
                "tempo_bt": track.get("tempo_bt"),
                "rms_mean": track.get("rms_mean"),
                "rms_std": track.get("rms_std"),
                "rms_min": track.get("rms_min"),
                "rms_max": track.get("rms_max"),
                "zcr_mean": track.get("zcr_mean"),
                "zcr_std": track.get("zcr_std"),
                "zcr_min": track.get("zcr_min"),
                "zcr_max": track.get("zcr_max"),
                "spec_centroid_mean": track.get("spec_centroid_mean"),
                "spec_centroid_std": track.get("spec_centroid_std"),
                "spec_centroid_min": track.get("spec_centroid_min"),
                "spec_centroid_max": track.get("spec_centroid_max"),
                "spec_bandwidth_mean": track.get("spec_bandwidth_mean"),
                "spec_bandwidth_std": track.get("spec_bandwidth_std"),
                "spec_bandwidth_min": track.get("spec_bandwidth_min"),
                "spec_bandwidth_max": track.get("spec_bandwidth_max"),
                "spec_contrast_1_mean": track.get("spec_contrast_1_mean"),
                "spec_contrast_1_std": track.get("spec_contrast_1_std"),
                "spec_contrast_1_min": track.get("spec_contrast_1_min"),
                "spec_contrast_1_max": track.get("spec_contrast_1_max"),
                "spec_contrast_2_mean": track.get("spec_contrast_2_mean"),
                "spec_contrast_2_std": track.get("spec_contrast_2_std"),
                "spec_contrast_2_min": track.get("spec_contrast_2_min"),
                "spec_contrast_2_max": track.get("spec_contrast_2_max"),
                "spec_contrast_3_mean": track.get("spec_contrast_3_mean"),
                "spec_contrast_3_std": track.get("spec_contrast_3_std"),
                "spec_contrast_3_min": track.get("spec_contrast_3_min"),
                "spec_contrast_3_max": track.get("spec_contrast_3_max"),
                "spec_contrast_4_mean": track.get("spec_contrast_4_mean"),
                "spec_contrast_4_std": track.get("spec_contrast_4_std"),
                "spec_contrast_4_min": track.get("spec_contrast_4_min"),
                "spec_contrast_4_max": track.get("spec_contrast_4_max"),
                "spec_contrast_5_mean": track.get("spec_contrast_5_mean"),
                "spec_contrast_5_std": track.get("spec_contrast_5_std"),
                "spec_contrast_5_min": track.get("spec_contrast_5_min"),
                "spec_contrast_5_max": track.get("spec_contrast_5_max"),
                "spec_contrast_6_mean": track.get("spec_contrast_6_mean"),
                "spec_contrast_6_std": track.get("spec_contrast_6_std"),
                "spec_contrast_6_min": track.get("spec_contrast_6_min"),
                "spec_contrast_6_max": track.get("spec_contrast_6_max"),
                "spec_contrast_7_mean": track.get("spec_contrast_7_mean"),
                "spec_contrast_7_std": track.get("spec_contrast_7_std"),
                "spec_contrast_7_min": track.get("spec_contrast_7_min"),
                "spec_contrast_7_max": track.get("spec_contrast_7_max"),
                "spec_flatness_mean": track.get("spec_flatness_mean"),
                "spec_flatness_std": track.get("spec_flatness_std"),
                "spec_flatness_min": track.get("spec_flatness_min"),
                "spec_flatness_max": track.get("spec_flatness_max"),
                "spec_rolloff_mean": track.get("spec_rolloff_mean"),
                "spec_rolloff_std": track.get("spec_rolloff_std"),
                "spec_rolloff_min": track.get("spec_rolloff_min"),
                "spec_rolloff_max": track.get("spec_rolloff_max"),
                "mfcc_1_mean": track.get("mfcc_1_mean"),
                "mfcc_1_std": track.get("mfcc_1_std"),
                "mfcc_1_min": track.get("mfcc_1_min"),
                "mfcc_1_max": track.get("mfcc_1_max"),
                "mfcc_2_mean": track.get("mfcc_2_mean"),
                "mfcc_2_std": track.get("mfcc_2_std"),
                "mfcc_2_min": track.get("mfcc_2_min"),
                "mfcc_2_max": track.get("mfcc_2_max"),
                "mfcc_3_mean": track.get("mfcc_3_mean"),
                "mfcc_3_std": track.get("mfcc_3_std"),
                "mfcc_3_min": track.get("mfcc_3_min"),
                "mfcc_3_max": track.get("mfcc_3_max"),
                "mfcc_4_mean": track.get("mfcc_4_mean"),
                "mfcc_4_std": track.get("mfcc_4_std"),
                "mfcc_4_min": track.get("mfcc_4_min"),
                "mfcc_4_max": track.get("mfcc_4_max"),
                "mfcc_5_mean": track.get("mfcc_5_mean"),
                "mfcc_5_std": track.get("mfcc_5_std"),
                "mfcc_5_min": track.get("mfcc_5_min"),
                "mfcc_5_max": track.get("mfcc_5_max"),
                "mfcc_6_mean": track.get("mfcc_6_mean"),
                "mfcc_6_std": track.get("mfcc_6_std"),
                "mfcc_6_min": track.get("mfcc_6_min"),
                "mfcc_6_max": track.get("mfcc_6_max"),
                "mfcc_7_mean": track.get("mfcc_7_mean"),
                "mfcc_7_std": track.get("mfcc_7_std"),
                "mfcc_7_min": track.get("mfcc_7_min"),
                "mfcc_7_max": track.get("mfcc_7_max"),
                "mfcc_8_mean": track.get("mfcc_8_mean"),
                "mfcc_8_std": track.get("mfcc_8_std"),
                "mfcc_8_min": track.get("mfcc_8_min"),
                "mfcc_8_max": track.get("mfcc_8_max"),
                "mfcc_9_mean": track.get("mfcc_9_mean"),
                "mfcc_9_std": track.get("mfcc_9_std"),
                "mfcc_9_min": track.get("mfcc_9_min"),
                "mfcc_9_max": track.get("mfcc_9_max"),
                "mfcc_10_mean": track.get("mfcc_10_mean"),
                "mfcc_10_std": track.get("mfcc_10_std"),
                "mfcc_10_min": track.get("mfcc_10_min"),
                "mfcc_10_max": track.get("mfcc_10_max"),
                "mfcc_11_mean": track.get("mfcc_11_mean"),
                "mfcc_11_std": track.get("mfcc_11_std"),
                "mfcc_11_min": track.get("mfcc_11_min"),
                "mfcc_11_max": track.get("mfcc_11_max"),
                "mfcc_12_mean": track.get("mfcc_12_mean"),
                "mfcc_12_std": track.get("mfcc_12_std"),
                "mfcc_12_min": track.get("mfcc_12_min"),
                "mfcc_12_max": track.get("mfcc_12_max"),
                "mfcc_13_mean": track.get("mfcc_13_mean"),
                "mfcc_13_std": track.get("mfcc_13_std"),
                "mfcc_13_min": track.get("mfcc_13_min"),
                "mfcc_13_max": track.get("mfcc_13_max"),
                "chromagram_1_mean": track.get("chromagram_1_mean"),
                "chromagram_1_std": track.get("chromagram_1_std"),
                "chromagram_1_min": track.get("chromagram_1_min"),
                "chromagram_1_max": track.get("chromagram_1_max"),
                "chromagram_2_mean": track.get("chromagram_2_mean"),
                "chromagram_2_std": track.get("chromagram_2_std"),
                "chromagram_2_min": track.get("chromagram_2_min"),
                "chromagram_2_max": track.get("chromagram_2_max"),
                "chromagram_3_mean": track.get("chromagram_3_mean"),
                "chromagram_3_std": track.get("chromagram_3_std"),
                "chromagram_3_min": track.get("chromagram_3_min"),
                "chromagram_3_max": track.get("chromagram_3_max"),
                "chromagram_4_mean": track.get("chromagram_4_mean"),
                "chromagram_4_std": track.get("chromagram_4_std"),
                "chromagram_4_min": track.get("chromagram_4_min"),
                "chromagram_4_max": track.get("chromagram_4_max"),
                "chromagram_5_mean": track.get("chromagram_5_mean"),
                "chromagram_5_std": track.get("chromagram_5_std"),
                "chromagram_5_min": track.get("chromagram_5_min"),
                "chromagram_5_max": track.get("chromagram_5_max"),
                "chromagram_6_mean": track.get("chromagram_6_mean"),
                "chromagram_6_std": track.get("chromagram_6_std"),
                "chromagram_6_min": track.get("chromagram_6_min"),
                "chromagram_6_max": track.get("chromagram_6_max"),
                "chromagram_7_mean": track.get("chromagram_7_mean"),
                "chromagram_7_std": track.get("chromagram_7_std"),
                "chromagram_7_min": track.get("chromagram_7_min"),
                "chromagram_7_max": track.get("chromagram_7_max"),
                "chromagram_8_mean": track.get("chromagram_8_mean"),
                "chromagram_8_std": track.get("chromagram_8_std"),
                "chromagram_8_min": track.get("chromagram_8_min"),
                "chromagram_8_max": track.get("chromagram_8_max"),
                "chromagram_9_mean": track.get("chromagram_9_mean"),
                "chromagram_9_std": track.get("chromagram_9_std"),
                "chromagram_9_min": track.get("chromagram_9_min"),
                "chromagram_9_max": track.get("chromagram_9_max"),
                "chromagram_10_mean": track.get("chromagram_10_mean"),
                "chromagram_10_std": track.get("chromagram_10_std"),
                "chromagram_10_min": track.get("chromagram_10_min"),
                "chromagram_10_max": track.get("chromagram_10_max"),
                "chromagram_11_mean": track.get("chromagram_11_mean"),
                "chromagram_11_std": track.get("chromagram_11_std"),
                "chromagram_11_min": track.get("chromagram_11_min"),
                "chromagram_11_max": track.get("chromagram_11_max"),
                "chromagram_12_mean": track.get("chromagram_12_mean"),
                "chromagram_12_std": track.get("chromagram_12_std"),
                "chromagram_12_min": track.get("chromagram_12_min"),
                "chromagram_12_max": track.get("chromagram_12_max"),
            }

            track_genre = track.get("genre").lower()

            for genre in mhe_genres_dict:
                row[genre] = 1 if genre.lower() == track_genre else 0

            track_seeds = track.get("seeds")

            for seed in mhe_seeds_dict:
                row[seed] = 1 if seed in track_seeds else 0

            writer.writerow(row)

            index += 1
            row_count += 1

    print("Successfully exported to csv!")
    print(f"Row Count: {row_count}")

# write_csv()

semantic_vector_path = r"server\model\dataset\semantic_data.csv"

semantic_csv_headers = (
    [
        "index",
        "track",
        "artist",
        "number_of_emotion_tags",
        "valence_tags",
        "arousal_tags",
        "dominance_tags",
    ]
    + mhe_genres_dict
    + mhe_seeds_dict
)

# Writes the file for ONLY the semantics of the samples
def write_semantic_vectors():
    index = 0

    with open(semantic_vector_path, "w", newline="", encoding="utf-8") as music_csv:
        writer = csv.DictWriter(music_csv, fieldnames=semantic_csv_headers)
        writer.writeheader()

        for track in uncleaned_dataset:
            row = {
                "index": index,
                "track": track.get("track"), # To drop during learning
                "artist": track.get("artist"), # To drop during learning (bring back if penalizing)
                "number_of_emotion_tags": track.get("number_of_emotion_tags"), # Keep??
                "valence_tags": track.get("valence_tags"),
                "arousal_tags": track.get("arousal_tags"),
                "dominance_tags": track.get("dominance_tags"),
            }

            track_genre = track.get("genre").lower()

            for genre in mhe_genres_dict:
                row[genre] = 1 if genre.lower() == track_genre else 0

            track_seeds = track.get("seeds")

            for seed in mhe_seeds_dict:
                row[seed] = 1 if seed in track_seeds else 0

            writer.writerow(row)

            index += 1

    print("Successfully exported to csv!")
    print(f"Row Count: {index}")

import numpy as np

# Writes the file for ONLY the auditory data tensors
def write_audio_tensors():
    data_array = []

    index = 0

    for track in uncleaned_dataset:
        track_array = [index,
                        track.get("tempo"),
                        track.get("tempo_bt"),
                        track.get("rms_mean"),
                        track.get("rms_std"),
                        track.get("rms_min"),
                        track.get("rms_max"),
                        track.get("zcr_mean"),
                        track.get("zcr_std"),
                        track.get("zcr_min"),
                        track.get("zcr_max"),
                        track.get("spec_centroid_mean"),
                        track.get("spec_centroid_std"),
                        track.get("spec_centroid_min"),
                        track.get("spec_centroid_max"),
                        track.get("spec_bandwidth_mean"),
                        track.get("spec_bandwidth_std"),
                        track.get("spec_bandwidth_min"),
                        track.get("spec_bandwidth_max"),
                        track.get("spec_contrast_1_mean"),
                        track.get("spec_contrast_1_std"),
                        track.get("spec_contrast_1_min"),
                        track.get("spec_contrast_1_max"),
                        track.get("spec_contrast_2_mean"),
                        track.get("spec_contrast_2_std"),
                        track.get("spec_contrast_2_min"),
                        track.get("spec_contrast_2_max"),
                        track.get("spec_contrast_3_mean"),
                        track.get("spec_contrast_3_std"),
                        track.get("spec_contrast_3_min"),
                        track.get("spec_contrast_3_max"),
                        track.get("spec_contrast_4_mean"),
                        track.get("spec_contrast_4_std"),
                        track.get("spec_contrast_4_min"),
                        track.get("spec_contrast_4_max"),
                        track.get("spec_contrast_5_mean"),
                        track.get("spec_contrast_5_std"),
                        track.get("spec_contrast_5_min"),
                        track.get("spec_contrast_5_max"),
                        track.get("spec_contrast_6_mean"),
                        track.get("spec_contrast_6_std"),
                        track.get("spec_contrast_6_min"),
                        track.get("spec_contrast_6_max"),
                        track.get("spec_contrast_7_mean"),
                        track.get("spec_contrast_7_std"),
                        track.get("spec_contrast_7_min"),
                        track.get("spec_contrast_7_max"),
                        track.get("spec_flatness_mean"),
                        track.get("spec_flatness_std"),
                        track.get("spec_flatness_min"),
                        track.get("spec_flatness_max"),
                        track.get("spec_rolloff_mean"),
                        track.get("spec_rolloff_std"),
                        track.get("spec_rolloff_min"),
                        track.get("spec_rolloff_max"),
                        track.get("mfcc_1_mean"),
                        track.get("mfcc_1_std"),
                        track.get("mfcc_1_min"),
                        track.get("mfcc_1_max"),
                        track.get("mfcc_2_mean"),
                        track.get("mfcc_2_std"),
                        track.get("mfcc_2_min"),
                        track.get("mfcc_2_max"),
                        track.get("mfcc_3_mean"),
                        track.get("mfcc_3_std"),
                        track.get("mfcc_3_min"),
                        track.get("mfcc_3_max"),
                        track.get("mfcc_4_mean"),
                        track.get("mfcc_4_std"),
                        track.get("mfcc_4_min"),
                        track.get("mfcc_4_max"),
                        track.get("mfcc_5_mean"),
                        track.get("mfcc_5_std"),
                        track.get("mfcc_5_min"),
                        track.get("mfcc_5_max"),
                        track.get("mfcc_6_mean"),
                        track.get("mfcc_6_std"),
                        track.get("mfcc_6_min"),
                        track.get("mfcc_6_max"),
                        track.get("mfcc_7_mean"),
                        track.get("mfcc_7_std"),
                        track.get("mfcc_7_min"),
                        track.get("mfcc_7_max"),
                        track.get("mfcc_8_mean"),
                        track.get("mfcc_8_std"),
                        track.get("mfcc_8_min"),
                        track.get("mfcc_8_max"),
                        track.get("mfcc_9_mean"),
                        track.get("mfcc_9_std"),
                        track.get("mfcc_9_min"),
                        track.get("mfcc_9_max"),
                        track.get("mfcc_10_mean"),
                        track.get("mfcc_10_std"),
                        track.get("mfcc_10_min"),
                        track.get("mfcc_10_max"),
                        track.get("mfcc_11_mean"),
                        track.get("mfcc_11_std"),
                        track.get("mfcc_11_min"),
                        track.get("mfcc_11_max"),
                        track.get("mfcc_12_mean"),
                        track.get("mfcc_12_std"),
                        track.get("mfcc_12_min"),
                        track.get("mfcc_12_max"),
                        track.get("mfcc_13_mean"),
                        track.get("mfcc_13_std"),
                        track.get("mfcc_13_min"),
                        track.get("mfcc_13_max"),
                        track.get("chromagram_1_mean"),
                        track.get("chromagram_1_std"),
                        track.get("chromagram_1_min"),
                        track.get("chromagram_1_max"),
                        track.get("chromagram_2_mean"),
                        track.get("chromagram_2_std"),
                        track.get("chromagram_2_min"),
                        track.get("chromagram_2_max"),
                        track.get("chromagram_3_mean"),
                        track.get("chromagram_3_std"),
                        track.get("chromagram_3_min"),
                        track.get("chromagram_3_max"),
                        track.get("chromagram_4_mean"),
                        track.get("chromagram_4_std"),
                        track.get("chromagram_4_min"),
                        track.get("chromagram_4_max"),
                        track.get("chromagram_5_mean"),
                        track.get("chromagram_5_std"),
                        track.get("chromagram_5_min"),
                        track.get("chromagram_5_max"),
                        track.get("chromagram_6_mean"),
                        track.get("chromagram_6_std"),
                        track.get("chromagram_6_min"),
                        track.get("chromagram_6_max"),
                        track.get("chromagram_7_mean"),
                        track.get("chromagram_7_std"),
                        track.get("chromagram_7_min"),
                        track.get("chromagram_7_max"),
                        track.get("chromagram_8_mean"),
                        track.get("chromagram_8_std"),
                        track.get("chromagram_8_min"),
                        track.get("chromagram_8_max"),
                        track.get("chromagram_9_mean"),
                        track.get("chromagram_9_std"),
                        track.get("chromagram_9_min"),
                        track.get("chromagram_9_max"),
                        track.get("chromagram_10_mean"),
                        track.get("chromagram_10_std"),
                        track.get("chromagram_10_min"),
                        track.get("chromagram_10_max"),
                        track.get("chromagram_11_mean"),
                        track.get("chromagram_11_std"),
                        track.get("chromagram_11_min"),
                        track.get("chromagram_11_max"),
                        track.get("chromagram_12_mean"),
                        track.get("chromagram_12_std"),
                        track.get("chromagram_12_min"),
                        track.get("chromagram_12_max"),
                    ]

        data_array.append(track_array) # Append the completed tensor into the tensor array

        track_array = [] # Clear the track tensor for the next iteration
        index += 1 # Increment the index

    np.save(r"server\model\dataset\audio_data.npy", data_array)
    print("Successfully exported to csv!")
    print(f"Tensor Count: {index}")

audio_csv_path = r"server\model\dataset\pre_audio_data.csv"

audio_csv_headers = (
    [
        "index",
        "tempo",
        "tempo_bt",
        "rms_mean",
        "rms_std",
        "rms_min",
        "rms_max",
        "zcr_mean",
        "zcr_std",
        "zcr_min",
        "zcr_max",
        "spec_centroid_mean",
        "spec_centroid_std",
        "spec_centroid_min",
        "spec_centroid_max",
        "spec_bandwidth_mean",
        "spec_bandwidth_std",
        "spec_bandwidth_min",
        "spec_bandwidth_max",
        "spec_contrast_1_mean",
        "spec_contrast_1_std",
        "spec_contrast_1_min",
        "spec_contrast_1_max",
        "spec_contrast_2_mean",
        "spec_contrast_2_std",
        "spec_contrast_2_min",
        "spec_contrast_2_max",
        "spec_contrast_3_mean",
        "spec_contrast_3_std",
        "spec_contrast_3_min",
        "spec_contrast_3_max",
        "spec_contrast_4_mean",
        "spec_contrast_4_std",
        "spec_contrast_4_min",
        "spec_contrast_4_max",
        "spec_contrast_5_mean",
        "spec_contrast_5_std",
        "spec_contrast_5_min",
        "spec_contrast_5_max",
        "spec_contrast_6_mean",
        "spec_contrast_6_std",
        "spec_contrast_6_min",
        "spec_contrast_6_max",
        "spec_contrast_7_mean",
        "spec_contrast_7_std",
        "spec_contrast_7_min",
        "spec_contrast_7_max",
        "spec_flatness_mean",
        "spec_flatness_std",
        "spec_flatness_min",
        "spec_flatness_max",
        "spec_rolloff_mean",
        "spec_rolloff_std",
        "spec_rolloff_min",
        "spec_rolloff_max",
        "mfcc_1_mean",
        "mfcc_1_std",
        "mfcc_1_min",
        "mfcc_1_max",
        "mfcc_2_mean",
        "mfcc_2_std",
        "mfcc_2_min",
        "mfcc_2_max",
        "mfcc_3_mean",
        "mfcc_3_std",
        "mfcc_3_min",
        "mfcc_3_max",
        "mfcc_4_mean",
        "mfcc_4_std",
        "mfcc_4_min",
        "mfcc_4_max",
        "mfcc_5_mean",
        "mfcc_5_std",
        "mfcc_5_min",
        "mfcc_5_max",
        "mfcc_6_mean",
        "mfcc_6_std",
        "mfcc_6_min",
        "mfcc_6_max",
        "mfcc_7_mean",
        "mfcc_7_std",
        "mfcc_7_min",
        "mfcc_7_max",
        "mfcc_8_mean",
        "mfcc_8_std",
        "mfcc_8_min",
        "mfcc_8_max",
        "mfcc_9_mean",
        "mfcc_9_std",
        "mfcc_9_min",
        "mfcc_9_max",
        "mfcc_10_mean",
        "mfcc_10_std",
        "mfcc_10_min",
        "mfcc_10_max",
        "mfcc_11_mean",
        "mfcc_11_std",
        "mfcc_11_min",
        "mfcc_11_max",
        "mfcc_12_mean",
        "mfcc_12_std",
        "mfcc_12_min",
        "mfcc_12_max",
        "mfcc_13_mean",
        "mfcc_13_std",
        "mfcc_13_min",
        "mfcc_13_max",
        "chromagram_1_mean",
        "chromagram_1_std",
        "chromagram_1_min",
        "chromagram_1_max",
        "chromagram_2_mean",
        "chromagram_2_std",
        "chromagram_2_min",
        "chromagram_2_max",
        "chromagram_3_mean",
        "chromagram_3_std",
        "chromagram_3_min",
        "chromagram_3_max",
        "chromagram_4_mean",
        "chromagram_4_std",
        "chromagram_4_min",
        "chromagram_4_max",
        "chromagram_5_mean",
        "chromagram_5_std",
        "chromagram_5_min",
        "chromagram_5_max",
        "chromagram_6_mean",
        "chromagram_6_std",
        "chromagram_6_min",
        "chromagram_6_max",
        "chromagram_7_mean",
        "chromagram_7_std",
        "chromagram_7_min",
        "chromagram_7_max",
        "chromagram_8_mean",
        "chromagram_8_std",
        "chromagram_8_min",
        "chromagram_8_max",
        "chromagram_9_mean",
        "chromagram_9_std",
        "chromagram_9_min",
        "chromagram_9_max",
        "chromagram_10_mean",
        "chromagram_10_std",
        "chromagram_10_min",
        "chromagram_10_max",
        "chromagram_11_mean",
        "chromagram_11_std",
        "chromagram_11_min",
        "chromagram_11_max",
        "chromagram_12_mean",
        "chromagram_12_std",
        "chromagram_12_min",
        "chromagram_12_max",
        ]
    )

def write_audio_csv():
    index = 0

    with open(audio_csv_path, "w", newline="", encoding="utf-8") as music_csv:
        writer = csv.DictWriter(music_csv, fieldnames=audio_csv_headers)
        writer.writeheader()

        for track in uncleaned_dataset:
            row = {
                "index": index,
                "tempo": track.get("tempo"),
                "tempo_bt": track.get("tempo_bt"),
                "rms_mean": track.get("rms_mean"),
                "rms_std": track.get("rms_std"),
                "rms_min": track.get("rms_min"),
                "rms_max": track.get("rms_max"),
                "zcr_mean": track.get("zcr_mean"),
                "zcr_std": track.get("zcr_std"),
                "zcr_min": track.get("zcr_min"),
                "zcr_max": track.get("zcr_max"),
                "spec_centroid_mean": track.get("spec_centroid_mean"),
                "spec_centroid_std": track.get("spec_centroid_std"),
                "spec_centroid_min": track.get("spec_centroid_min"),
                "spec_centroid_max": track.get("spec_centroid_max"),
                "spec_bandwidth_mean": track.get("spec_bandwidth_mean"),
                "spec_bandwidth_std": track.get("spec_bandwidth_std"),
                "spec_bandwidth_min": track.get("spec_bandwidth_min"),
                "spec_bandwidth_max": track.get("spec_bandwidth_max"),
                "spec_contrast_1_mean": track.get("spec_contrast_1_mean"),
                "spec_contrast_1_std": track.get("spec_contrast_1_std"),
                "spec_contrast_1_min": track.get("spec_contrast_1_min"),
                "spec_contrast_1_max": track.get("spec_contrast_1_max"),
                "spec_contrast_2_mean": track.get("spec_contrast_2_mean"),
                "spec_contrast_2_std": track.get("spec_contrast_2_std"),
                "spec_contrast_2_min": track.get("spec_contrast_2_min"),
                "spec_contrast_2_max": track.get("spec_contrast_2_max"),
                "spec_contrast_3_mean": track.get("spec_contrast_3_mean"),
                "spec_contrast_3_std": track.get("spec_contrast_3_std"),
                "spec_contrast_3_min": track.get("spec_contrast_3_min"),
                "spec_contrast_3_max": track.get("spec_contrast_3_max"),
                "spec_contrast_4_mean": track.get("spec_contrast_4_mean"),
                "spec_contrast_4_std": track.get("spec_contrast_4_std"),
                "spec_contrast_4_min": track.get("spec_contrast_4_min"),
                "spec_contrast_4_max": track.get("spec_contrast_4_max"),
                "spec_contrast_5_mean": track.get("spec_contrast_5_mean"),
                "spec_contrast_5_std": track.get("spec_contrast_5_std"),
                "spec_contrast_5_min": track.get("spec_contrast_5_min"),
                "spec_contrast_5_max": track.get("spec_contrast_5_max"),
                "spec_contrast_6_mean": track.get("spec_contrast_6_mean"),
                "spec_contrast_6_std": track.get("spec_contrast_6_std"),
                "spec_contrast_6_min": track.get("spec_contrast_6_min"),
                "spec_contrast_6_max": track.get("spec_contrast_6_max"),
                "spec_contrast_7_mean": track.get("spec_contrast_7_mean"),
                "spec_contrast_7_std": track.get("spec_contrast_7_std"),
                "spec_contrast_7_min": track.get("spec_contrast_7_min"),
                "spec_contrast_7_max": track.get("spec_contrast_7_max"),
                "spec_flatness_mean": track.get("spec_flatness_mean"),
                "spec_flatness_std": track.get("spec_flatness_std"),
                "spec_flatness_min": track.get("spec_flatness_min"),
                "spec_flatness_max": track.get("spec_flatness_max"),
                "spec_rolloff_mean": track.get("spec_rolloff_mean"),
                "spec_rolloff_std": track.get("spec_rolloff_std"),
                "spec_rolloff_min": track.get("spec_rolloff_min"),
                "spec_rolloff_max": track.get("spec_rolloff_max"),
                "mfcc_1_mean": track.get("mfcc_1_mean"),
                "mfcc_1_std": track.get("mfcc_1_std"),
                "mfcc_1_min": track.get("mfcc_1_min"),
                "mfcc_1_max": track.get("mfcc_1_max"),
                "mfcc_2_mean": track.get("mfcc_2_mean"),
                "mfcc_2_std": track.get("mfcc_2_std"),
                "mfcc_2_min": track.get("mfcc_2_min"),
                "mfcc_2_max": track.get("mfcc_2_max"),
                "mfcc_3_mean": track.get("mfcc_3_mean"),
                "mfcc_3_std": track.get("mfcc_3_std"),
                "mfcc_3_min": track.get("mfcc_3_min"),
                "mfcc_3_max": track.get("mfcc_3_max"),
                "mfcc_4_mean": track.get("mfcc_4_mean"),
                "mfcc_4_std": track.get("mfcc_4_std"),
                "mfcc_4_min": track.get("mfcc_4_min"),
                "mfcc_4_max": track.get("mfcc_4_max"),
                "mfcc_5_mean": track.get("mfcc_5_mean"),
                "mfcc_5_std": track.get("mfcc_5_std"),
                "mfcc_5_min": track.get("mfcc_5_min"),
                "mfcc_5_max": track.get("mfcc_5_max"),
                "mfcc_6_mean": track.get("mfcc_6_mean"),
                "mfcc_6_std": track.get("mfcc_6_std"),
                "mfcc_6_min": track.get("mfcc_6_min"),
                "mfcc_6_max": track.get("mfcc_6_max"),
                "mfcc_7_mean": track.get("mfcc_7_mean"),
                "mfcc_7_std": track.get("mfcc_7_std"),
                "mfcc_7_min": track.get("mfcc_7_min"),
                "mfcc_7_max": track.get("mfcc_7_max"),
                "mfcc_8_mean": track.get("mfcc_8_mean"),
                "mfcc_8_std": track.get("mfcc_8_std"),
                "mfcc_8_min": track.get("mfcc_8_min"),
                "mfcc_8_max": track.get("mfcc_8_max"),
                "mfcc_9_mean": track.get("mfcc_9_mean"),
                "mfcc_9_std": track.get("mfcc_9_std"),
                "mfcc_9_min": track.get("mfcc_9_min"),
                "mfcc_9_max": track.get("mfcc_9_max"),
                "mfcc_10_mean": track.get("mfcc_10_mean"),
                "mfcc_10_std": track.get("mfcc_10_std"),
                "mfcc_10_min": track.get("mfcc_10_min"),
                "mfcc_10_max": track.get("mfcc_10_max"),
                "mfcc_11_mean": track.get("mfcc_11_mean"),
                "mfcc_11_std": track.get("mfcc_11_std"),
                "mfcc_11_min": track.get("mfcc_11_min"),
                "mfcc_11_max": track.get("mfcc_11_max"),
                "mfcc_12_mean": track.get("mfcc_12_mean"),
                "mfcc_12_std": track.get("mfcc_12_std"),
                "mfcc_12_min": track.get("mfcc_12_min"),
                "mfcc_12_max": track.get("mfcc_12_max"),
                "mfcc_13_mean": track.get("mfcc_13_mean"),
                "mfcc_13_std": track.get("mfcc_13_std"),
                "mfcc_13_min": track.get("mfcc_13_min"),
                "mfcc_13_max": track.get("mfcc_13_max"),
                "chromagram_1_mean": track.get("chromagram_1_mean"),
                "chromagram_1_std": track.get("chromagram_1_std"),
                "chromagram_1_min": track.get("chromagram_1_min"),
                "chromagram_1_max": track.get("chromagram_1_max"),
                "chromagram_2_mean": track.get("chromagram_2_mean"),
                "chromagram_2_std": track.get("chromagram_2_std"),
                "chromagram_2_min": track.get("chromagram_2_min"),
                "chromagram_2_max": track.get("chromagram_2_max"),
                "chromagram_3_mean": track.get("chromagram_3_mean"),
                "chromagram_3_std": track.get("chromagram_3_std"),
                "chromagram_3_min": track.get("chromagram_3_min"),
                "chromagram_3_max": track.get("chromagram_3_max"),
                "chromagram_4_mean": track.get("chromagram_4_mean"),
                "chromagram_4_std": track.get("chromagram_4_std"),
                "chromagram_4_min": track.get("chromagram_4_min"),
                "chromagram_4_max": track.get("chromagram_4_max"),
                "chromagram_5_mean": track.get("chromagram_5_mean"),
                "chromagram_5_std": track.get("chromagram_5_std"),
                "chromagram_5_min": track.get("chromagram_5_min"),
                "chromagram_5_max": track.get("chromagram_5_max"),
                "chromagram_6_mean": track.get("chromagram_6_mean"),
                "chromagram_6_std": track.get("chromagram_6_std"),
                "chromagram_6_min": track.get("chromagram_6_min"),
                "chromagram_6_max": track.get("chromagram_6_max"),
                "chromagram_7_mean": track.get("chromagram_7_mean"),
                "chromagram_7_std": track.get("chromagram_7_std"),
                "chromagram_7_min": track.get("chromagram_7_min"),
                "chromagram_7_max": track.get("chromagram_7_max"),
                "chromagram_8_mean": track.get("chromagram_8_mean"),
                "chromagram_8_std": track.get("chromagram_8_std"),
                "chromagram_8_min": track.get("chromagram_8_min"),
                "chromagram_8_max": track.get("chromagram_8_max"),
                "chromagram_9_mean": track.get("chromagram_9_mean"),
                "chromagram_9_std": track.get("chromagram_9_std"),
                "chromagram_9_min": track.get("chromagram_9_min"),
                "chromagram_9_max": track.get("chromagram_9_max"),
                "chromagram_10_mean": track.get("chromagram_10_mean"),
                "chromagram_10_std": track.get("chromagram_10_std"),
                "chromagram_10_min": track.get("chromagram_10_min"),
                "chromagram_10_max": track.get("chromagram_10_max"),
                "chromagram_11_mean": track.get("chromagram_11_mean"),
                "chromagram_11_std": track.get("chromagram_11_std"),
                "chromagram_11_min": track.get("chromagram_11_min"),
                "chromagram_11_max": track.get("chromagram_11_max"),
                "chromagram_12_mean": track.get("chromagram_12_mean"),
                "chromagram_12_std": track.get("chromagram_12_std"),
                "chromagram_12_min": track.get("chromagram_12_min"),
                "chromagram_12_max": track.get("chromagram_12_max"),
            }

            writer.writerow(row)

            index += 1

    print("Successfully exported to csv!")
    print(f"Row Count: {index}")

print("Starting semantic split...")

# write_semantic_vectors()

print("\nStarting audio tensor split...")

# write_audio_tensors()

write_audio_csv()

print("\nDone!")

########################################### CLEANSING ############################################
# import pandas as pd

# csv_path = r"server\model\music_dataset.csv"

# df = pd.read_csv(csv_path)

# df_new = df.drop(labels=["track", "artist", "number_of_emotion_tags", "valence_tags", "arousal_tags", "dominance_tags"], axis=1)

# df_duplicates = df[df["spotify_id"].duplicated()]

# print(df["spotify_id"].value_counts()[lambda x: x > 1])
# print(df_duplicates)